[Setup]
; Basic Application Info
AppId={{8A192C23-83E4-4899-B81E-E72026BCA3A4}
AppName=Database Studio
AppVersion=1.0
AppPublisher=Md Yeamin Habib
DefaultDirName={autopf}\Database Studio
DefaultGroupName=Database Studio
UninstallDisplayIcon={app}\app.exe

; Setup Executable & Custom Icon Configuration
SetupIconFile=static\icon.ico
OutputDir=Output
OutputBaseFilename=DatabaseStudio_Setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Primary application executable
Source: "dist\app\app.exe"; DestDir: "{app}"; Flags: ignoreversion

; All supporting files and subdirectories generated by PyInstaller
Source: "dist\app\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Start Menu Shortcuts
Name: "{group}\Database Studio"; Filename: "{app}\app.exe"; IconFilename: "{app}\_internal\static\icon.ico"
Name: "{group}\{cm:UninstallProgram,Database Studio}"; Filename: "{uninstallexe}"

; Desktop Shortcut
Name: "{autodesktop}\Database Studio"; Filename: "{app}\app.exe"; IconFilename: "{app}\_internal\static\icon.ico"; Tasks: desktopicon

[Run]
; Launch option after installation finishes
Filename: "{app}\app.exe"; Description: "{cm:LaunchProgram,Database Studio}"; Flags: nowait postinstall skipifsilent